# Generated by Django 5.1.4 on 2024-12-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registrationapp', '0002_alter_student_course_alter_student_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='housnag', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
